version: '3.1'

services:
    teamcity:
        image: jetbrains/teamcity-server
        volumes:
            - ./data/server/datadir:/data/teamcity_server/datadir
            - ./data/server/logs:/opt/teamcity/logs
        ports:
            - 8111:8111
    teamcity-agent:
        image: pfries/teamcity-agent-with-docker-compose
        build: ./agent
        volumes:
            - ./data/agent:/data/teamcity_agent/conf
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            SERVER_URL: http://teamcity:8111
